PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xml: <https://www.w3.org/TR/xml#>

SELECT ?obsoleteclass ?obsoletelabel ?replacementclass

WHERE {
	?obsoleteclass a owl:Class .
	?obsoleteclass oboInOwl:inSubset "annotare_terms" .
	?obsoleteclass rdfs:label ?obsoletelabel .
	?obsoleteclass rdfs:subClassOf <http://www.geneontology.org/formats/oboInOwl#ObsoleteClass> .
	OPTIONAL {?obsoleteclass obo:IAO_0100001 ?replacementclass .}
	}
